In [3]:
import numpy as np

In [35]:
omega_x = -0.2
omega_y = 0.2
h = 1.2
p = 0.275

In [36]:
R = np.array([[np.cos(np.asin(omega_x))*np.cos(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x))))), -np.cos(np.asin(omega_x))*np.sin(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x))))), np.sin(np.asin(omega_x))],
              [np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x))*np.cos(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x))))), np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.cos(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x)))))-np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x))*np.sin(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x))))), -np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.cos(np.asin(omega_x))],
              [np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x)))))-np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x))*np.cos(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x))))), np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.cos(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x)))))+np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x))*np.sin(np.tan((np.sin(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.sin(np.asin(omega_x)))/(np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))+np.cos(np.asin(omega_x))))), np.cos(np.asin(-omega_y/np.cos(np.asin(omega_x))))*np.cos(np.asin(omega_x))]])

In [46]:
R

array([[ 0.97958303, -0.02042276, -0.2       ],
       [-0.02042276,  0.97788138,  0.2       ],
       [ 0.19149172, -0.2081608 ,  0.9591663 ]])

In [45]:
R[1][0] = R[0][1]
#R[0][1] = R[1][0]
R

array([[ 0.97958303, -0.02042276, -0.2       ],
       [-0.02042276,  0.97788138,  0.2       ],
       [ 0.19149172, -0.2081608 ,  0.9591663 ]])

In [47]:
O_7y = -R[1][0]*p
O_7x = (p*(R[0][0]-R[1][1]))/2
O_7z = h

In [48]:
O_7 = np.array([O_7x, O_7y, O_7z])

In [51]:
alpha = 4*np.pi/3 # ali 2*np.pi/3 ali 4*np.pi/3

In [52]:
R_z = np.array([[np.cos(alpha), -np.sin(alpha), 0],
                [np.sin(alpha), np.cos(alpha), 0],
                [0, 0, 1]])
R_z

array([[-0.5      ,  0.8660254,  0.       ],
       [-0.8660254, -0.5      ,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [49]:
alpha = 0
R_z = np.array([[np.cos(alpha), -np.sin(alpha), 0],
                [np.sin(alpha), np.cos(alpha), 0],
                [0, 0, 1]])
vektor_0 = O_7 + (R@R_z)@np.array([p, 0, 0])
alpha = 2*np.pi/3 
R_z = np.array([[np.cos(alpha), -np.sin(alpha), 0],
                [np.sin(alpha), np.cos(alpha), 0],
                [0, 0, 1]])
vektor_1 = O_7 + (R@R_z)@np.array([p, 0, 0])
alpha = 4*np.pi/3 
R_z = np.array([[np.cos(alpha), -np.sin(alpha), 0],
                [np.sin(alpha), np.cos(alpha), 0],
                [0, 0, 1]])
vektor_2 = O_7 + (R@R_z)@np.array([p, 0, 0])



In [41]:
vektor_0, vektor_1, vektor_2

(array([0.26961931, 0.        , 1.25266022]),
 array([-0.13932251,  0.2160527 ,  1.12409494]),
 array([-0.12959487, -0.24972587,  1.22324484]))

In [50]:
vektor_0, vektor_1, vektor_2

(array([0.26961931, 0.        , 1.25266022]),
 array([-0.13932251,  0.24131367,  1.12409494]),
 array([-0.12959487, -0.22446489,  1.22324484]))

In [51]:
vozlisca = np.array([[vektor_0[0], vektor_0[2]], [vektor_1[0], vektor_1[2]], [vektor_2[0], vektor_2[2]]])

In [55]:
#vozlisca = np.array([[np.sqrt(vektor_0[0]**2+vektor_0[1]**2), vektor_0[2]], [np.sqrt(vektor_1[0]**2+vektor_1[1]**2), vektor_1[2]], [np.sqrt(vektor_2[0]**2+vektor_2[1]**2), vektor_2[2]]])

In [52]:
vozlisca

array([[ 0.26961931,  1.25266022],
       [-0.13932251,  1.12409494],
       [-0.12959487,  1.22324484]])

In [44]:
calculate_angles(vozlisca, 0.7, 0.775, 0.55)

(np.float64(-71.41375201095987),
 np.float64(-62.82950370536553),
 np.float64(-70.0152630003184),
 np.float64(-133.81917544523256),
 np.float64(-144.3134567112014),
 np.float64(-136.7308548141921))

In [ ]:
calculate_angles(vozlisca, 0.7, 0.775, 0.55)

In [27]:
def calculate_angles(vertices=list, l_1=float, l_2=float, b=float):
    '''Izračuna kote glede na podana vozlišča.

    vertices - matrika točk v x-z ravnini oblike [[x1, z1], [x2, z2], [x3, z3]], l_1 - dolžina spodnje roke, l_2 - dolžina zgornje roke, b - radij sponjega kroga.

    '''
    A_1 = 2*l_1*np.cos(0)*(-vertices[0][0] + b*np.cos(0))
    A_2 = 2*l_1*np.cos(2*np.pi/3)*(-vertices[1][0] + b*np.cos(2*np.pi/3))
    A_3 = 2*l_1*np.cos(4*np.pi/3)*(-vertices[2][0] + b*np.cos(4*np.pi/3))

    B_1 = 2*l_1*vertices[0][1]*np.cos(0)**2
    B_2 = 2*l_1*vertices[1][1]*np.cos(2*np.pi/3)**2
    B_3 = 2*l_1*vertices[2][1]*np.cos(4*np.pi/3)**2

    C_1 = vertices[0][0]**2-2*b*vertices[0][0]*np.cos(0)+np.cos(0)**2*(b**2+l_1**2-l_2**2+vertices[0][1]**2)
    C_2 = vertices[1][0]**2-2*b*vertices[1][0]*np.cos(2*np.pi/3)+np.cos(2*np.pi/3)**2*(b**2+l_1**2-l_2**2+vertices[1][1]**2)
    C_3 = vertices[2][0]**2-2*b*vertices[2][0]*np.cos(4*np.pi/3)+np.cos(4*np.pi/3)**2*(b**2+l_1**2-l_2**2+vertices[2][1]**2)

    En_1_m = 2*np.atan2(-B_1-np.sqrt(A_1**2+B_1**2-C_1**2), C_1-A_1)
    En_1_p = 2*np.atan2(-B_1+np.sqrt(A_1**2+B_1**2-C_1**2), C_1-A_1)
    En_2_p = 2*np.atan2(-B_2+np.sqrt(A_2**2+B_2**2-C_2**2), C_2-A_2)
    En_2_m = 2*np.atan2(-B_2-np.sqrt(A_2**2+B_2**2-C_2**2), C_2-A_2)
    En_3_p = 2*np.atan2(-B_3+np.sqrt(A_3**2+B_3**2-C_3**2), C_3-A_3)
    En_3_m = 2*np.atan2(-B_3-np.sqrt(A_3**2+B_3**2-C_3**2), C_3-A_3)

    return np.rad2deg(En_1_p), np.rad2deg(En_2_p), np.rad2deg(En_3_p), np.rad2deg(En_1_m), np.rad2deg(En_2_m), np.rad2deg(En_3_m)

In [135]:
from funkcije import izracun_kotov


ImportError: cannot import name 'izracun_kotov' from 'funkcije' (c:\David\Paralelni_manipulator\dinamski_model\funkcije.py)